name: build
run-name: build
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install mono-devel
        run: sudo apt-get install -y mono-devel
      - name: Clone UnkownShadow200/ClassiCube
        run: git clone https://github.com/UnknownShadow200/ClassiCube
      - name: Replace instances of '../ClassiCube-src' with 'ClassiCube' in Api.h
        run: sed -i -e 's/\.\.\/ClassiCube\-src/ClassiCube/g' Api.h
      - name: Replace instances of '../ClassiCube-src' with 'ClassiCube' in MonoPlugin.c
        run: sed -i -e 's/\.\.\/ClassiCube\-src/ClassiCube/g' MonoPlugin.c
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Complile for Linux 64-bit
        id: compile
        run: ./build
  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Package into a tar
        run: tar -cf archive.tar MonoPlugin.so MonoPluginLoader.dll
      - name: Compress the tar with gzip
        run: gzip archive.tar
        
  upload:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: ./ClassiCube/.github/actions/upload_build
        with:
          SOURCE_FILE: 'archive.tar.gz'
          DEST_NAME: 'ClassiCube-Linux64'
